[tool.poetry]
name = "repl_python3_mcgill-phys-hack-2021"
version = "0.1.0"
description = ""
authors = ["itsjoeoui <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pygame = "^2.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
